spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: USER-SERVICE-POOL
      username: tester@%
      password: 1234qewr
      jdbc-url: jdbc:mariadb://localhost:3306/toy_project