spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/toy_project
    username: tester
    password: 1234qwer
    hikari:
      pool-name: USER-SERVICE-POOL